#!/usr/bin/env python3
"""Generate web-optimized derivatives from scripts/_originals/ and write
_data/dimensions.yml (real pixel w/h + orientation + available widths).

- Image.MAX_IMAGE_PIXELS = None: work #14 is ~92MP and would otherwise raise
  Pillow's DecompressionBomb guard.
- exif_transpose: bake correct rotation so orientation is derived from true pixels,
  not the canvas-inch caption (the two disagree for ~1/3 of the works).
- Never upscale: tiers are capped at the source width.
"""
import os
from PIL import Image, ImageOps

Image.MAX_IMAGE_PIXELS = None

from _works import SLUGS

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ORIG = os.path.join(HERE, "_originals")
OUT_WORKS = os.path.join(ROOT, "assets", "img", "works")
OUT_ABOUT = os.path.join(ROOT, "assets", "img", "about")
OUT_META = os.path.join(ROOT, "assets", "img", "meta")
DATA = os.path.join(ROOT, "_data", "dimensions.yml")
for d in (OUT_WORKS, OUT_ABOUT, OUT_META):
    os.makedirs(d, exist_ok=True)

WEBP_WIDTHS = [400, 800, 1200, 2000]
JPG_WIDTHS = [800, 1200]
WEBP_Q = 80
JPG_Q = 82


def find_original(i, slug):
    for ext in (".jpeg", ".jpg", ".png"):
        p = os.path.join(ORIG, f"{i:02d}-{slug}{ext}")
        if os.path.exists(p):
            return p
    return None


def load(path):
    im = Image.open(path)
    im = ImageOps.exif_transpose(im)
    if im.mode != "RGB":
        im = im.convert("RGB")
    return im


def tiers_for(source_w, widths):
    t = [w for w in widths if w <= source_w]
    # give small sources their native max so the lightbox isn't stuck at 800
    if source_w < widths[-1] and (not t or t[-1] < source_w):
        t.append(source_w)
    return t or [source_w]


def emit(im, out_base, widths, fmt, q):
    sw, sh = im.size
    written = []
    for w in tiers_for(sw, widths):
        th = round(sh * w / sw)
        rim = im.resize((w, th), Image.LANCZOS)
        if fmt == "webp":
            outp = f"{out_base}-{w}.webp"
            rim.save(outp, "WEBP", quality=q, method=6)
        else:
            outp = f"{out_base}-{w}.jpg"
            rim.save(outp, "JPEG", quality=q, progressive=True, optimize=True)
        written.append(w)
    return written


def dir_size(path):
    total = 0
    for root, _, files in os.walk(path):
        for fn in files:
            total += os.path.getsize(os.path.join(root, fn))
    return total


dims = {}
soft = []
missing = []

print(f"{'#':>2}  {'slug':34}  {'pixels':>11}  {'orient':9}  webp tiers")
print("-" * 78)
for i, slug in enumerate(SLUGS, start=1):
    src = find_original(i, slug)
    if not src:
        print(f"{i:02d}  {slug:34}  MISSING ORIGINAL")
        missing.append(slug)
        continue
    im = load(src)
    w, h = im.size
    orientation = "landscape" if w > h else "portrait"
    webp = emit(im, os.path.join(OUT_WORKS, slug), WEBP_WIDTHS, "webp", WEBP_Q)
    jpg = emit(im, os.path.join(OUT_WORKS, slug), JPG_WIDTHS, "jpg", JPG_Q)
    dims[slug] = {"w": w, "h": h, "orientation": orientation, "webp": webp, "jpg": jpg}
    flag = ""
    if w < 1200:
        soft.append((slug, w))
        flag = "  << low-res source"
    print(f"{i:02d}  {slug:34}  {w:5}x{h:<5}  {orientation:9}  {webp}{flag}")

# ABOUT portrait
portrait_src = os.path.join(ORIG, "portrait.jpg")
if os.path.exists(portrait_src):
    im = load(portrait_src)
    w, h = im.size
    pw = emit(im, os.path.join(OUT_ABOUT, "portrait"), [400, 800, 1200], "webp", WEBP_Q)
    pj = emit(im, os.path.join(OUT_ABOUT, "portrait"), [800], "jpg", JPG_Q)
    dims["portrait"] = {"w": w, "h": h, "orientation": "landscape" if w > h else "portrait", "webp": pw, "jpg": pj}
    print(f"--  portrait{'':28}  {w:5}x{h:<5}  ({'landscape' if w>h else 'portrait'})")
else:
    print("--  portrait  MISSING (about page will need a manual portrait.jpg)")

# OG share card (1200x630, cover-cropped from Arbor)
arbor_src = find_original(1, "arbor")
if arbor_src:
    im = load(arbor_src)
    ImageOps.fit(im, (1200, 630), Image.LANCZOS).save(os.path.join(OUT_META, "og-image.jpg"), "JPEG", quality=85, optimize=True)
    print("--  og-image.jpg  1200x630")

# write _data/dimensions.yml
lines = ["# AUTO-GENERATED by scripts/build_images.py — do not edit by hand.", ""]
for slug, d in dims.items():
    lines += [
        f'"{slug}":',
        f"  w: {d['w']}",
        f"  h: {d['h']}",
        f"  orientation: {d['orientation']}",
        f"  webp: [{', '.join(map(str, d['webp']))}]",
        f"  jpg: [{', '.join(map(str, d['jpg']))}]",
        "",
    ]
with open(DATA, "w") as f:
    f.write("\n".join(lines))

print("\n" + "=" * 60)
print(f"Wrote {DATA}  ({len(dims)} entries)")
print(f"Committed assets/img total: {dir_size(os.path.join(ROOT,'assets','img'))/1024/1024:.1f} MB")
n_land = sum(1 for s in SLUGS if dims.get(s, {}).get('orientation') == 'landscape')
print(f"Orientation: {len(SLUGS)-n_land} portrait, {n_land} landscape")
if soft:
    print("Low-res sources (consider re-supplying higher-res):")
    for slug, w in soft:
        print(f"   - {slug} ({w}px wide)")
if missing:
    print(f"MISSING ORIGINALS: {missing}")
